unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

setw -g mode-keys vi

set -s escape-time 0

set -g mouse on

bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

set -g status-left " "
set -g status-right "%b-%e %I:%M%p "

set -g status-bg blue
set -g window-status-format " #I:#W #{?window_last_flag,L, }#{?window_zoomed_flag,Z, }"
set -g window-status-current-format "#[bg=brightgreen] #I:#W #{?window_last_flag,L, }#{?window_zoomed_flag,Z, }#[default]"
